name: Build Libs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Build Libs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]

    steps:
    - uses: actions/checkout@v3
      with:
          lfs: true

    - name: Configure CMake (Shared)
      run: cmake -B ${{github.workspace}}/build_shared -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_UTILITIES=OFF -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=ON -DBUILD_PYTHON_BINDINGS=OFF
      
    - name: Configure CMake (Static)
      run: cmake -B ${{github.workspace}}/build_static -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_UTILITIES=ON -DBUILD_TESTS=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_PYTHON_BINDINGS=OFF

    - name: Build (Shared)
      run: cmake --build ${{github.workspace}}/build_shared --config ${{env.BUILD_TYPE}}
    
    - name: Build (Static)
      run: cmake --build ${{github.workspace}}/build_static --config ${{env.BUILD_TYPE}}

    - name: Test (Shared)
      working-directory: ${{github.workspace}}/build_shared
      run: ctest -C ${{env.BUILD_TYPE}}
    
    - name: Test (Static)
      working-directory: ${{github.workspace}}/build_static
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Install(Shared)
      run: cmake --install ${{github.workspace}}/build_shared --prefix ${{github.workspace}}/install --strip

    - name: Install(Static)
      run: cmake --install ${{github.workspace}}/build_static --prefix ${{github.workspace}}/install --strip

    - uses: actions/upload-artifact@v3
      with:
        name: rssdk-${{ matrix.os }}
        path: ${{github.workspace}}/install

