name: ROS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
      ROS_PARALLEL_JOBS: '-j8 -l6'
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          cmake --version
          mkdir build
          cd build
          ls -l
          cmake ..
          make
